@Api_HostAddress = http://localhost:5191
@baseUrl = http://localhost:5191/api

GET {{Api_HostAddress}}/weatherforecast/
Accept: application/json

### Prueba de autenticación con Google
POST {{baseUrl}}/auth/google
Content-Type: application/json

{
  "idToken": "GOOGLE_ID_TOKEN_HERE"
}
