name: Build and deploy ASP.Net Core app to Azure Web App - PracticaCore

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.x'

      - name: Build with dotnet
        run: dotnet build PracticaCore.sln --configuration Release

      - name: Run Tests
        run: dotnet test Tests/Tests.csproj --no-build --configuration Release --verbosity normal --filter "FullyQualifiedName!~Tests.Integration.Documents.DocumentControllerTests"

      - name: dotnet publish
        run: dotnet publish Api/Api.csproj --configuration Release --output publish

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_67749FBB0EAB49559F85AB3091188289 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_FA64EEF39FE74E509FB26E378E41E817 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4294A74A267247169F2AC6874F333573 }}

      - name: Deploy to Azure Web App
        run: |
          az webapp deploy --resource-group PracticaCore --name PracticaCore --src-path ./publish --type zip
