name: Build and Test ASP.NET Core App

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.x'

      - name: Build with dotnet
        run: dotnet build PracticaCore.sln --configuration Release

      - name: Run Tests
        run: dotnet test Tests/Tests.csproj --no-build --configuration Release --verbosity normal --filter "FullyQualifiedName!~Tests.Integration.Documents.DocumentControllerTests"

      - name: dotnet publish
        run: dotnet publish Api/Api.csproj -c Release -o "${{ github.workspace }}/publish"

      - name: Upload published artifact
        uses: actions/upload-artifact@v4
        with:
          name: PracticaCore-publish
          path: ${{ github.workspace }}/publish
